### ISSUE TITLE
Error in python script

### ISSUE THREAD

**Issue by hscleandro** [prouast/cryptocurrency-analysis#1]
I tried to run your code but an error occurred.

![image](https://user-images.githubusercontent.com/4611796/32565019-ae6f705c-c494-11e7-8ea5-d260e3eab660.png)

Can you help me?

**Comment by prouast** [comment]
Thanks for bringing this to my attention. It should work fine now without the `min_cap` argument. Since there many currencies on coinmarketcap now, you can specify the minimum market cap of currencies to be scraped, e.g.: `python scrape.py 1000000`.
