### ISSUE TITLE
No table called 'currency'/missing documentation

### ISSUE THREAD

**Issue by ThomasPepperz** [prouast/cryptocurrency-analysis#5]
**The Code:**
con <- dbConnect(RSQLite::SQLite(), dbname='database.db') # Database connection
currencies <- dbGetQuery(con, "SELECT * FROM currency") # Import currencies

**The Error:**
Error in result_create(conn@ptr, statement) : no such table: currency

Additionally, you provide some more documentation? Perhaps a list of all of the tables available and `variables`? By the way, I'm liking what I'm seeing. Great job with the frequent updates.

**Comment by prouast** [comment]
Thanks Thomas. To replicate, first head over to [coinmarketcap-scraper](https://github.com/prouast/coinmarketcap-scraper); this lets you download data from coinmarketcap into a local database. The script analysis.R can then be run on this database - copy the database file to your R working directory.

**Comment by ThomasPepperz** [comment]
Excellent. Issue resolved!
